# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndstats', '0018_auto_20150517_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNASSIGNED'), (1, 'CONSORTIUM'), (2, 'EMPIRE')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNASSIGNED'), (1, 'CONSORTIUM'), (2, 'EMPIRE')], null=True),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='team',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNASSIGNED'), (1, 'CONSORTIUM'), (2, 'EMPIRE')]),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='what',
            field=models.IntegerField(choices=[(0, 'death'), (1, 'destroyed'), (2, 'built')]),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='commander',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNASSIGNED'), (1, 'CONSORTIUM'), (2, 'EMPIRE')], null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='team_current',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNASSIGNED'), (1, 'CONSORTIUM'), (2, 'EMPIRE')], null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='team_final',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UNASSIGNED'), (1, 'CONSORTIUM'), (2, 'EMPIRE')], null=True),
        ),
    ]
