# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndstats', '0019_auto_20160710_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('weight', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(upload_to='')),
                ('is_available', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
    ]
