# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndstats', '0021_auto_20161121_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('ip', 'port')]),
        ),
    ]
