# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndstats', '0022_auto_20180628_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodProduct',
        ),
    ]
